Hot-fix to run assembly without plasmids reconstruction
causing the Error in rule align_plasmid_assembly_graph

Traceback (most recent call last):
  File "/data/Genomes/2023-07_hibc_additions/genome-assembly/.snakemake/scripts/tmpf6j2spao.wrapper.py", line 68, in <m
odule>
    shell(
  File "/home/uni-aachen/mambaforge/envs/snakemake/lib/python3.11/site-packages/snakemake/shell.py", line 294, in __new
__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  (bwa mem -t 16  results/plasmid_reconstruction/LK310Iso12/L
K310Iso12_assembly_graph.nodes.fasta results/trimmed/LK310Iso12.1.phix.fastq results/trimmed/LK310Iso12.2.phix.fastq |
samtools view  --threads 15 -o results/plasmid_reconstruction/LK310Iso12/LK310Iso12_reads_pe.bam --output-fmt BAM)  2>
logs/plasmid_reconstruction/LK310Iso12_align_assembly_graph.log' returned non-zero exit status 1